// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKx4rvIgiI3deHmK57eTS0rw_Ismr0tM0',
    appId: '1:234728912401:web:66335985e91bb598f863b0',
    messagingSenderId: '234728912401',
    projectId: 'appdeviagens-53e73',
    authDomain: 'appdeviagens-53e73.firebaseapp.com',
    storageBucket: 'appdeviagens-53e73.firebasestorage.app',
    measurementId: 'G-DH5D4TZT2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDICV_O_5_XyXRzHHmH24t3h71_jZalncw',
    appId: '1:234728912401:android:859a1b9dd4c609e0f863b0',
    messagingSenderId: '234728912401',
    projectId: 'appdeviagens-53e73',
    storageBucket: 'appdeviagens-53e73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-5wMFNVjc8LSM_C-gkxBIoAZSa3TTdS8',
    appId: '1:234728912401:ios:a998a8c325cc80a1f863b0',
    messagingSenderId: '234728912401',
    projectId: 'appdeviagens-53e73',
    storageBucket: 'appdeviagens-53e73.firebasestorage.app',
    iosClientId: '234728912401-klff2ja8bvtpuo0ctlf0rkn6h39l78gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIdiomas1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-5wMFNVjc8LSM_C-gkxBIoAZSa3TTdS8',
    appId: '1:234728912401:ios:a998a8c325cc80a1f863b0',
    messagingSenderId: '234728912401',
    projectId: 'appdeviagens-53e73',
    storageBucket: 'appdeviagens-53e73.firebasestorage.app',
    iosClientId: '234728912401-klff2ja8bvtpuo0ctlf0rkn6h39l78gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIdiomas1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKx4rvIgiI3deHmK57eTS0rw_Ismr0tM0',
    appId: '1:234728912401:web:0522293b0a15e689f863b0',
    messagingSenderId: '234728912401',
    projectId: 'appdeviagens-53e73',
    authDomain: 'appdeviagens-53e73.firebaseapp.com',
    storageBucket: 'appdeviagens-53e73.firebasestorage.app',
    measurementId: 'G-F184PKEK4Q',
  );

}